// <auto-generated/>
#nullable enable
// CS1591: XML doc comments are not required for auto-generated typed client code.
#pragma warning disable CS1591

using System;
using System.Collections.Generic;
using System.Globalization;
using System.Net;
using System.Net.Http;
using System.Net.Http.Json;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.Threading;
using System.Threading.Tasks;

namespace Inbox.Client;

public partial class SliceApiClient
{
    private readonly HttpClient _http;

    public SliceApiClient(HttpClient http)
    {
        _http = http ?? throw new ArgumentNullException(nameof(http));
        Feeds = new FeedsClient(_http, PrepareRequest);
        Items = new ItemsClient(_http, PrepareRequest);
        Share = new ShareClient(_http, PrepareRequest);
        Workspaces = new WorkspacesClient(_http, PrepareRequest);
    }

    public SliceApiClient(HttpMessageHandler handler) : this(new HttpClient(handler)) { }

    partial void OnRequestPreparing(HttpRequestMessage request);

    private void PrepareRequest(HttpRequestMessage request) => OnRequestPreparing(request);

    public FeedsClient Feeds { get; }
    public ItemsClient Items { get; }
    public ShareClient Share { get; }
    public WorkspacesClient Workspaces { get; }

    private static string FormatRouteValue<T>(T value)
        => Uri.EscapeDataString(Convert.ToString(value, CultureInfo.InvariantCulture) ?? string.Empty);

    private static async Task __ThrowApiException(HttpResponseMessage response, string operation, CancellationToken cancellationToken)
    {
        SliceProblemDetails? problem = null;
        try
        {
            var __body = await response.Content.ReadAsStringAsync(cancellationToken).ConfigureAwait(false);
            if (__body.Length > 0)
            {
                var __mediaType = response.Content.Headers.ContentType?.MediaType;
                if (__mediaType is "application/problem+json" or "application/json")
                {
                    problem = JsonSerializer.Deserialize(__body, SliceApiClientJsonContext.Default.SliceProblemDetails);
                }
            }
        }
        catch (Exception ex) when (ex is not OperationCanceledException) { }
        var __message = problem?.Title ?? $"{operation} failed: {(int)response.StatusCode} {response.ReasonPhrase}";
        throw new SliceApiException(__message, response.StatusCode, problem);
    }

    public sealed class FeedsClient
    {
        private readonly HttpClient _http;
        private readonly Action<HttpRequestMessage> _prepareRequest;

        internal FeedsClient(HttpClient http, Action<HttpRequestMessage> prepareRequest)
        {
            _http = http;
            _prepareRequest = prepareRequest;
        }

        public async Task<SliceApiClient.__SliceClientResponse<Inbox.Contracts.AddFeedResponse>> AddFeedAsync(Inbox.Contracts.AddFeedRequest req, CancellationToken cancellationToken = default)
        {
            var __url = $"/api/feeds";
            using var __message = new HttpRequestMessage(new HttpMethod("POST"), __url);
            __message.Content = JsonContent.Create(req, SliceApiClientJsonContext.Default.AddFeedRequest);
            _prepareRequest(__message);
            using var __response = await _http.SendAsync(__message, cancellationToken).ConfigureAwait(false);
            if (!__response.IsSuccessStatusCode)
            {
                await SliceApiClient.__ThrowApiException(__response, "AddFeed", cancellationToken).ConfigureAwait(false);
            }
            var __statusCode = (int)__response.StatusCode;
            var __location = __response.Headers.Location;
            var __body = await __response.Content.ReadFromJsonAsync(SliceApiClientJsonContext.Default.AddFeedResponse, cancellationToken).ConfigureAwait(false)
                ?? throw new HttpRequestException("Route 'Feeds.AddFeed' returned an empty response body.");
            return new SliceApiClient.__SliceClientResponse<Inbox.Contracts.AddFeedResponse>(__body, __statusCode, __location);
        }

        public async Task<SliceApiClient.__SliceClientResponse<Inbox.Contracts.GetFeedsResponse>> GetFeedsAsync(CancellationToken cancellationToken = default)
        {
            var __url = $"/api/feeds";
            using var __message = new HttpRequestMessage(HttpMethod.Get, __url);
            _prepareRequest(__message);
            using var __response = await _http.SendAsync(__message, cancellationToken).ConfigureAwait(false);
            if (!__response.IsSuccessStatusCode)
            {
                await SliceApiClient.__ThrowApiException(__response, "GetFeeds", cancellationToken).ConfigureAwait(false);
            }
            var __statusCode = (int)__response.StatusCode;
            var __location = __response.Headers.Location;
            var __body = await __response.Content.ReadFromJsonAsync(SliceApiClientJsonContext.Default.GetFeedsResponse, cancellationToken).ConfigureAwait(false)
                ?? throw new HttpRequestException("Route 'Feeds.GetFeeds' returned an empty response body.");
            return new SliceApiClient.__SliceClientResponse<Inbox.Contracts.GetFeedsResponse>(__body, __statusCode, __location);
        }

        public async Task<SliceApiClient.__SliceClientResponse<Inbox.Contracts.RefreshFeedsResponse>> RefreshAllFeedsAsync(CancellationToken cancellationToken = default)
        {
            var __url = $"/api/feeds/refresh-all";
            using var __message = new HttpRequestMessage(new HttpMethod("POST"), __url);
            _prepareRequest(__message);
            using var __response = await _http.SendAsync(__message, cancellationToken).ConfigureAwait(false);
            if (!__response.IsSuccessStatusCode)
            {
                await SliceApiClient.__ThrowApiException(__response, "RefreshAllFeeds", cancellationToken).ConfigureAwait(false);
            }
            var __statusCode = (int)__response.StatusCode;
            var __location = __response.Headers.Location;
            var __body = await __response.Content.ReadFromJsonAsync(SliceApiClientJsonContext.Default.RefreshFeedsResponse, cancellationToken).ConfigureAwait(false)
                ?? throw new HttpRequestException("Route 'Feeds.RefreshAllFeeds' returned an empty response body.");
            return new SliceApiClient.__SliceClientResponse<Inbox.Contracts.RefreshFeedsResponse>(__body, __statusCode, __location);
        }

        public async Task<SliceApiClient.__SliceClientResponse<Inbox.Contracts.RefreshFeedsResponse>> RefreshFeedsAsync(CancellationToken cancellationToken = default)
        {
            var __url = $"/api/feeds/refresh";
            using var __message = new HttpRequestMessage(new HttpMethod("POST"), __url);
            _prepareRequest(__message);
            using var __response = await _http.SendAsync(__message, cancellationToken).ConfigureAwait(false);
            if (!__response.IsSuccessStatusCode)
            {
                await SliceApiClient.__ThrowApiException(__response, "RefreshFeeds", cancellationToken).ConfigureAwait(false);
            }
            var __statusCode = (int)__response.StatusCode;
            var __location = __response.Headers.Location;
            var __body = await __response.Content.ReadFromJsonAsync(SliceApiClientJsonContext.Default.RefreshFeedsResponse, cancellationToken).ConfigureAwait(false)
                ?? throw new HttpRequestException("Route 'Feeds.RefreshFeeds' returned an empty response body.");
            return new SliceApiClient.__SliceClientResponse<Inbox.Contracts.RefreshFeedsResponse>(__body, __statusCode, __location);
        }
    }

    public sealed class ItemsClient
    {
        private readonly HttpClient _http;
        private readonly Action<HttpRequestMessage> _prepareRequest;

        internal ItemsClient(HttpClient http, Action<HttpRequestMessage> prepareRequest)
        {
            _http = http;
            _prepareRequest = prepareRequest;
        }

        public async Task<SliceApiClient.__SliceClientResponse> DeleteItemAsync(string id, CancellationToken cancellationToken = default)
        {
            var __url = $"/api/items/{SliceApiClient.FormatRouteValue(id)}";
            using var __message = new HttpRequestMessage(new HttpMethod("DELETE"), __url);
            _prepareRequest(__message);
            using var __response = await _http.SendAsync(__message, cancellationToken).ConfigureAwait(false);
            if (!__response.IsSuccessStatusCode)
            {
                await SliceApiClient.__ThrowApiException(__response, "DeleteItem", cancellationToken).ConfigureAwait(false);
            }
            var __statusCode = (int)__response.StatusCode;
            var __location = __response.Headers.Location;
            return new SliceApiClient.__SliceClientResponse(__statusCode, __location);
        }

        public async Task<SliceApiClient.__SliceClientResponse<Inbox.Contracts.GetItemResponse>> GetItemAsync(string id, CancellationToken cancellationToken = default)
        {
            var __url = $"/api/items/{SliceApiClient.FormatRouteValue(id)}";
            using var __message = new HttpRequestMessage(HttpMethod.Get, __url);
            _prepareRequest(__message);
            using var __response = await _http.SendAsync(__message, cancellationToken).ConfigureAwait(false);
            if (!__response.IsSuccessStatusCode)
            {
                await SliceApiClient.__ThrowApiException(__response, "GetItem", cancellationToken).ConfigureAwait(false);
            }
            var __statusCode = (int)__response.StatusCode;
            var __location = __response.Headers.Location;
            var __body = await __response.Content.ReadFromJsonAsync(SliceApiClientJsonContext.Default.GetItemResponse, cancellationToken).ConfigureAwait(false)
                ?? throw new HttpRequestException("Route 'Items.GetItem' returned an empty response body.");
            return new SliceApiClient.__SliceClientResponse<Inbox.Contracts.GetItemResponse>(__body, __statusCode, __location);
        }

        public async Task<SliceApiClient.__SliceClientResponse<Inbox.Contracts.GetItemsResponse>> GetItemsAsync(string q, string tag, string status, int? limit, int? offset, CancellationToken cancellationToken = default)
        {
            var __url = $"/api/items";
            var __query = new List<string>();
            if (q is not null)
                __query.Add("q=" + SliceApiClient.FormatRouteValue(q));
            if (tag is not null)
                __query.Add("tag=" + SliceApiClient.FormatRouteValue(tag));
            if (status is not null)
                __query.Add("status=" + SliceApiClient.FormatRouteValue(status));
            if (limit is not null)
                __query.Add("limit=" + SliceApiClient.FormatRouteValue(limit));
            if (offset is not null)
                __query.Add("offset=" + SliceApiClient.FormatRouteValue(offset));
            __url += "?" + string.Join("&", __query);
            using var __message = new HttpRequestMessage(HttpMethod.Get, __url);
            _prepareRequest(__message);
            using var __response = await _http.SendAsync(__message, cancellationToken).ConfigureAwait(false);
            if (!__response.IsSuccessStatusCode)
            {
                await SliceApiClient.__ThrowApiException(__response, "GetItems", cancellationToken).ConfigureAwait(false);
            }
            var __statusCode = (int)__response.StatusCode;
            var __location = __response.Headers.Location;
            var __body = await __response.Content.ReadFromJsonAsync(SliceApiClientJsonContext.Default.GetItemsResponse, cancellationToken).ConfigureAwait(false)
                ?? throw new HttpRequestException("Route 'Items.GetItems' returned an empty response body.");
            return new SliceApiClient.__SliceClientResponse<Inbox.Contracts.GetItemsResponse>(__body, __statusCode, __location);
        }

        public async Task<SliceApiClient.__SliceClientResponse<Inbox.Contracts.PostItemResponse>> PostItemAsync(Inbox.Contracts.PostItemRequest req, CancellationToken cancellationToken = default)
        {
            var __url = $"/api/items";
            using var __message = new HttpRequestMessage(new HttpMethod("POST"), __url);
            __message.Content = JsonContent.Create(req, SliceApiClientJsonContext.Default.PostItemRequest);
            _prepareRequest(__message);
            using var __response = await _http.SendAsync(__message, cancellationToken).ConfigureAwait(false);
            if (!__response.IsSuccessStatusCode)
            {
                await SliceApiClient.__ThrowApiException(__response, "PostItem", cancellationToken).ConfigureAwait(false);
            }
            var __statusCode = (int)__response.StatusCode;
            var __location = __response.Headers.Location;
            var __body = await __response.Content.ReadFromJsonAsync(SliceApiClientJsonContext.Default.PostItemResponse, cancellationToken).ConfigureAwait(false)
                ?? throw new HttpRequestException("Route 'Items.PostItem' returned an empty response body.");
            return new SliceApiClient.__SliceClientResponse<Inbox.Contracts.PostItemResponse>(__body, __statusCode, __location);
        }

        public async Task<SliceApiClient.__SliceClientResponse> UpdateItemAsync(string id, Inbox.Contracts.UpdateItemRequest req, CancellationToken cancellationToken = default)
        {
            var __url = $"/api/items/{SliceApiClient.FormatRouteValue(id)}";
            using var __message = new HttpRequestMessage(new HttpMethod("PATCH"), __url);
            __message.Content = JsonContent.Create(req, SliceApiClientJsonContext.Default.UpdateItemRequest);
            _prepareRequest(__message);
            using var __response = await _http.SendAsync(__message, cancellationToken).ConfigureAwait(false);
            if (!__response.IsSuccessStatusCode)
            {
                await SliceApiClient.__ThrowApiException(__response, "UpdateItem", cancellationToken).ConfigureAwait(false);
            }
            var __statusCode = (int)__response.StatusCode;
            var __location = __response.Headers.Location;
            return new SliceApiClient.__SliceClientResponse(__statusCode, __location);
        }
    }

    public sealed class ShareClient
    {
        private readonly HttpClient _http;
        private readonly Action<HttpRequestMessage> _prepareRequest;

        internal ShareClient(HttpClient http, Action<HttpRequestMessage> prepareRequest)
        {
            _http = http;
            _prepareRequest = prepareRequest;
        }

        public async Task<SliceApiClient.__SliceClientResponse<Inbox.Contracts.ShareResponse>> CreateShareAsync(string id, CancellationToken cancellationToken = default)
        {
            var __url = $"/api/items/{SliceApiClient.FormatRouteValue(id)}/share";
            using var __message = new HttpRequestMessage(new HttpMethod("POST"), __url);
            _prepareRequest(__message);
            using var __response = await _http.SendAsync(__message, cancellationToken).ConfigureAwait(false);
            if (!__response.IsSuccessStatusCode)
            {
                await SliceApiClient.__ThrowApiException(__response, "CreateShare", cancellationToken).ConfigureAwait(false);
            }
            var __statusCode = (int)__response.StatusCode;
            var __location = __response.Headers.Location;
            var __body = await __response.Content.ReadFromJsonAsync(SliceApiClientJsonContext.Default.ShareResponse, cancellationToken).ConfigureAwait(false)
                ?? throw new HttpRequestException("Route 'Share.CreateShare' returned an empty response body.");
            return new SliceApiClient.__SliceClientResponse<Inbox.Contracts.ShareResponse>(__body, __statusCode, __location);
        }

        public async Task<SliceApiClient.__SliceClientResponse> GetSharePageAsync(string token, CancellationToken cancellationToken = default)
        {
            var __url = $"/s/{SliceApiClient.FormatRouteValue(token)}";
            using var __message = new HttpRequestMessage(new HttpMethod("GET"), __url);
            _prepareRequest(__message);
            using var __response = await _http.SendAsync(__message, cancellationToken).ConfigureAwait(false);
            if (!__response.IsSuccessStatusCode)
            {
                await SliceApiClient.__ThrowApiException(__response, "GetSharePage", cancellationToken).ConfigureAwait(false);
            }
            var __statusCode = (int)__response.StatusCode;
            var __location = __response.Headers.Location;
            return new SliceApiClient.__SliceClientResponse(__statusCode, __location);
        }

        public async Task<SliceApiClient.__SliceClientResponse> RevokeShareAsync(string id, CancellationToken cancellationToken = default)
        {
            var __url = $"/api/items/{SliceApiClient.FormatRouteValue(id)}/share";
            using var __message = new HttpRequestMessage(new HttpMethod("DELETE"), __url);
            _prepareRequest(__message);
            using var __response = await _http.SendAsync(__message, cancellationToken).ConfigureAwait(false);
            if (!__response.IsSuccessStatusCode)
            {
                await SliceApiClient.__ThrowApiException(__response, "RevokeShare", cancellationToken).ConfigureAwait(false);
            }
            var __statusCode = (int)__response.StatusCode;
            var __location = __response.Headers.Location;
            return new SliceApiClient.__SliceClientResponse(__statusCode, __location);
        }
    }

    public sealed class WorkspacesClient
    {
        private readonly HttpClient _http;
        private readonly Action<HttpRequestMessage> _prepareRequest;

        internal WorkspacesClient(HttpClient http, Action<HttpRequestMessage> prepareRequest)
        {
            _http = http;
            _prepareRequest = prepareRequest;
        }

        public async Task<SliceApiClient.__SliceClientResponse<Inbox.Contracts.CreateWorkspaceResponse>> CreateWorkspaceAsync(CancellationToken cancellationToken = default)
        {
            var __url = $"/api/workspaces";
            using var __message = new HttpRequestMessage(new HttpMethod("POST"), __url);
            _prepareRequest(__message);
            using var __response = await _http.SendAsync(__message, cancellationToken).ConfigureAwait(false);
            if (!__response.IsSuccessStatusCode)
            {
                await SliceApiClient.__ThrowApiException(__response, "CreateWorkspace", cancellationToken).ConfigureAwait(false);
            }
            var __statusCode = (int)__response.StatusCode;
            var __location = __response.Headers.Location;
            var __body = await __response.Content.ReadFromJsonAsync(SliceApiClientJsonContext.Default.CreateWorkspaceResponse, cancellationToken).ConfigureAwait(false)
                ?? throw new HttpRequestException("Route 'Workspaces.CreateWorkspace' returned an empty response body.");
            return new SliceApiClient.__SliceClientResponse<Inbox.Contracts.CreateWorkspaceResponse>(__body, __statusCode, __location);
        }

        public async Task<SliceApiClient.__SliceClientResponse<Inbox.Contracts.CreateWorkspaceResponse>> EnsureDemoAsync(CancellationToken cancellationToken = default)
        {
            var __url = $"/api/demo";
            using var __message = new HttpRequestMessage(new HttpMethod("POST"), __url);
            _prepareRequest(__message);
            using var __response = await _http.SendAsync(__message, cancellationToken).ConfigureAwait(false);
            if (!__response.IsSuccessStatusCode)
            {
                await SliceApiClient.__ThrowApiException(__response, "EnsureDemo", cancellationToken).ConfigureAwait(false);
            }
            var __statusCode = (int)__response.StatusCode;
            var __location = __response.Headers.Location;
            var __body = await __response.Content.ReadFromJsonAsync(SliceApiClientJsonContext.Default.CreateWorkspaceResponse, cancellationToken).ConfigureAwait(false)
                ?? throw new HttpRequestException("Route 'Workspaces.EnsureDemo' returned an empty response body.");
            return new SliceApiClient.__SliceClientResponse<Inbox.Contracts.CreateWorkspaceResponse>(__body, __statusCode, __location);
        }
    }

    public sealed class SliceProblemDetails
    {
        public string? Type { get; set; }
        public string? Title { get; set; }
        public int? Status { get; set; }
        public string? Detail { get; set; }
        public IReadOnlyDictionary<string, string[]>? Errors { get; set; }
    }

    public class SliceApiException : HttpRequestException
    {
        public SliceProblemDetails? Problem { get; }
        public IReadOnlyDictionary<string, string[]>? Errors => Problem?.Errors;
        public SliceApiException(string message, HttpStatusCode statusCode, SliceProblemDetails? problem)
            : base(message, null, statusCode)
        {
            Problem = problem;
        }
    }

    /// <summary>Carries a typed response body together with the HTTP status code and optional Location header.</summary>
    public readonly struct __SliceClientResponse<T>
    {
        /// <summary>The deserialized response body.</summary>
        public T Value { get; }
        /// <summary>The HTTP status code (e.g. 200, 201).</summary>
        public int StatusCode { get; }
        /// <summary>The Location header value, or <see langword="null"/> when absent.</summary>
        public Uri? Location { get; }
        /// <param name="value">Deserialized response body.</param>
        /// <param name="statusCode">HTTP status code.</param>
        /// <param name="location">Location header (e.g. for 201 Created responses).</param>
        public __SliceClientResponse(T value, int statusCode, Uri? location)
        {
            Value = value;
            StatusCode = statusCode;
            Location = location;
        }
    }

    /// <summary>Carries the HTTP status code and optional Location header for status-only responses.</summary>
    public readonly struct __SliceClientResponse
    {
        /// <summary>The HTTP status code (e.g. 204).</summary>
        public int StatusCode { get; }
        /// <summary>The Location header value, or <see langword="null"/> when absent.</summary>
        public Uri? Location { get; }
        /// <param name="statusCode">HTTP status code.</param>
        /// <param name="location">Location header.</param>
        public __SliceClientResponse(int statusCode, Uri? location)
        {
            StatusCode = statusCode;
            Location = location;
        }
    }
}

[JsonSourceGenerationOptions(PropertyNameCaseInsensitive = true, PropertyNamingPolicy = JsonKnownNamingPolicy.CamelCase)]
[JsonSerializable(typeof(Inbox.Contracts.CreateWorkspaceResponse))]
[JsonSerializable(typeof(Inbox.Contracts.GetFeedsResponse))]
[JsonSerializable(typeof(Inbox.Contracts.AddFeedRequest))]
[JsonSerializable(typeof(Inbox.Contracts.AddFeedResponse))]
[JsonSerializable(typeof(Inbox.Contracts.RefreshFeedsResponse))]
[JsonSerializable(typeof(Inbox.Contracts.GetItemsResponse))]
[JsonSerializable(typeof(Inbox.Contracts.PostItemRequest))]
[JsonSerializable(typeof(Inbox.Contracts.PostItemResponse))]
[JsonSerializable(typeof(Inbox.Contracts.GetItemResponse))]
[JsonSerializable(typeof(Inbox.Contracts.UpdateItemRequest))]
[JsonSerializable(typeof(Inbox.Contracts.ShareResponse))]
[JsonSerializable(typeof(SliceApiClient.SliceProblemDetails))]
internal sealed partial class SliceApiClientJsonContext : JsonSerializerContext
{
}
